### ISSUE TITLE
Button onclick issue

### ISSUE THREAD

**Issue by zansangeeth** [zansangeeth/LunchTray#2]
hi @ezatpanah, 
I am trying to implement the button click listener on fragment but I can't implement the Toast 
**actual scenario of this app listed pizza items in listview I need select the pizza and click ADD it will send the data to orders fragment** 
help me to fix this as soon as possible.

thanks

**Comment by ezatpanah** [comment]
Hi , 
today I am so busy , and so sorry 🙏
you can ask your question here : https://stackoverflow.com/ and others can help you as soon as possible 😊
best regards

**Comment by zansangeeth** [comment]
Hi,
it's ok. no worries.
thanks and regards
